openapi: 3.0.1
info:
  title: ms-event-management API
  description: API for managing events
  version: 1.0.0
servers:
  - url: http://localhost:8080/br/com/compass/eventmanagement/v1
paths:
  /create-event:
    post:
      summary: Create a new event
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                eventName:
                  type: string
                dateTime:
                  type: string
                  format: date-time
                cep:
                  type: string
              required:
                - eventName
                - dateTime
                - cep
      responses:
        '200':
          description: Event created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  eventName:
                    type: string
                  dateTime:
                    type: string
                    format: date-time
                  cep:
                    type: string
                  logradouro:
                    type: string
                  bairro:
                    type: string
                  cidade:
                    type: string
                  uf:
                    type: string
  /get-event/{id}:
    get:
      summary: Get event by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Event details
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  eventName:
                    type: string
                  dateTime:
                    type: string
                    format: date-time
                  cep:
                    type: string
                  logradouro:
                    type: string
                  bairro:
                    type: string
                  cidade:
                    type: string
                  uf:
                    type: string
  /get-all-events:
    get:
      summary: Get all events
      responses:
        '200':
          description: List of all events
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    eventName:
                      type: string
                    dateTime:
                      type: string
                      format: date-time
                    cep:
                      type: string
                    logradouro:
                      type: string
                    bairro:
                      type: string
                    cidade:
                      type: string
                    uf:
                      type: string
  /get-all-events/sorted:
    get:
      summary: Get all events sorted
      responses:
        '200':
          description: List of all events sorted
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    eventName:
                      type: string
                    dateTime:
                      type: string
                      format: date-time
                    cep:
                      type: string
                    logradouro:
                      type: string
                    bairro:
                      type: string
                    cidade:
                      type: string
                    uf:
                      type: string
  /update-event/{id}:
    put:
      summary: Update an event by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                eventName:
                  type: string
                dateTime:
                  type: string
                  format: date-time
                cep:
                  type: string
              required:
                - eventName
                - dateTime
                - cep
      responses:
        '200':
          description: Event updated successfully
        '409':
          description: Conflict - Tickets linked to this event
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /delete-event/{id}:
    delete:
      summary: Delete an event by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Event deleted successfully
        '409':
          description: Conflict - Tickets linked to this event
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string